### ISSUE TITLE
ipython_quickstart duplicate

### ISSUE THREAD

**Issue by drnextgis** [OSGeo/OSGeoLive-doc#41]
There are two the same files but with different name: IPython_quickstart.rst and ipython_quickstart.rst.

**Comment by kalxas** [comment]
Thanks for the feedback.
It seems that only ipython_quickstart is used in the overview page.
@darkblue-b any comments?

**Comment by kalxas** [comment]
reported to trac, thanks.
https://trac.osgeo.org/osgeo/ticket/1610
